--- #YAML:1.0
name:               TinyDNS-Reader
version:            0.7.2
abstract:           Parser for TinyDNS records.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:    0
    Test::NoTabs:  0
    Test::Pod:     0
    Test::Strict:  0
requires:
    perl:  5.008
resources:
    bugtracker:  https://github.com/skx/TinyDNS--Reader/issues
    homepage:    https://github.com/skx/TinyDNS--Reader/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/TinyDNS--Reader.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
